cycleEventsPlanner/bikes/urls.py
from django.urls import path, include

from bikes.views import BikeAddView, BikeDetailView, BikeUpdateView, BikeDeleteView, BikeListView, MyBikesListView

urlpatterns = [
    path('add/', BikeAddView.as_view(), name='add-bike'),
    path('all/', BikeListView.as_view(), name='all-bikes'),
    path('my-bikes/', MyBikesListView.as_view(), name='my-bikes'),
    path('<int:pk>/', include([
        path('', BikeDetailView.as_view(), name='bike-details'),
        path('edit/', BikeUpdateView.as_view(), name='edit-bike'),
        path('delete/', BikeDeleteView.as_view(), name='delete-bike'),
    ]))
]

cycleEventsPlanner/cycleEventsPlanner/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('accounts/', include('accounts.urls')),
    path('bikes/', include('bikes.urls')),
    path('events/', include('events.urls')),
    path('routes/', include('routes.urls')),
    path('gallery/', include('gallery.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cycleEventsPlanner/bikes/models.py
from django.contrib.auth import get_user_model
from django.db import models

from bikes.choices import BikeTypeChoices, BikeGeometryChoices

UserModel = get_user_model()

# Create your models here.
class Bike(models.Model):
    manufacturer = models.CharField(
        max_length=50,
    )

    model = models.CharField(
        max_length=50,
    )

    type = models.CharField(
        max_length=50,
        choices=BikeTypeChoices.choices,
        default=BikeTypeChoices.MTB
    )

    geometry = models.CharField(
        max_length=100,
        choices=BikeGeometryChoices.choices,
        default=BikeGeometryChoices.HARDTAIL,
    )

    is_ebike = models.BooleanField(
        default=False,
    )

    year = models.PositiveIntegerField(
        null=True,
        blank=True,
    )

    wheel_size = models.FloatField(
        null=True,
        blank=True,
    )

    is_mullet = models.BooleanField(
        default=False,
    )

    weight = models.FloatField(
        null=True,
        blank=True,
    )

    picture = models.URLField(
        null=True,
        blank=True,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
        related_name='bikes',
    )

    def __str__(self):
        return f'{self.manufacturer} {self.model}'

cycleEventsPlanner/bikes/forms.py
from django import forms

from bikes.models import Bike


class BikeBaseForm(forms.ModelForm):
    class Meta:
        model = Bike
        exclude = ['user', ]
        labels = {
            'manufacturer': 'Bike Manufacturer',
            'model': 'Model Name',
            'type': 'Bike Type',
            'geometry': 'Bike Geometry',
            'is_ebike': 'Is this an E-Bike?',
            'year': 'Year Produced',
            'wheel_size': 'Wheel Size',
            'is_mullet': 'Is this a Mullet? (front and rear wheel sizes are different)',
            'weight': 'Weight',
            'picture': 'Link to photo',
        }

        widgets = {
            'manufacturer': forms.TextInput(
                attrs={
                    'placeholder': 'Your bike manufacturer brand:'
                }
            ),
            'model': forms.TextInput(
                attrs={
                    'placeholder': 'Your bike model name:'
                }
            ),
            'year': forms.NumberInput(
                attrs={
                    'placeholder': 'Your bike year of production (optional):'
                }
            ),
            'wheel_size': forms.NumberInput(
                attrs={
                    'placeholder': 'Your bike wheel size (in INCHES) (optional):'
                }
            ),
            'weight': forms.NumberInput(
                attrs={
                    'placeholder': 'Your bike weight (in KGS) (optional):'
                }
            ),
            'picture': forms.TextInput(
                attrs={
                    'placeholder': 'Link to an image of your bike (optional):'
                }
            )
        }


class BikeCreateForm(BikeBaseForm):
    pass


class BikeEditForm(BikeBaseForm):
    pass


class BikeDeleteForm(BikeBaseForm):
    pass

cycleEventsPlanner/bikes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from bikes.forms import BikeCreateForm, BikeEditForm
from bikes.models import Bike


# Create your views here.
class BikeAddView(LoginRequiredMixin, CreateView):
    model = Bike
    form_class = BikeCreateForm
    template_name = 'bikes/add-bike.html'
    success_url = reverse_lazy('my-bikes')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class BikeListView(LoginRequiredMixin, ListView):
    model = Bike
    context_object_name = 'bikes'
    template_name = 'bikes/bikes-list.html'


class MyBikesListView(LoginRequiredMixin, ListView):
    model = Bike
    context_object_name = 'bikes'
    template_name = 'bikes/my-bikes.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user__pk=self.request.user.pk)
        return queryset


class BikeDetailView(LoginRequiredMixin, DetailView):
    model = Bike
    context_object_name = 'bike'
    template_name = 'bikes/bike-details.html'


class BikeUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Bike
    form_class = BikeEditForm
    context_object_name = 'bike'
    template_name = 'bikes/edit-bike.html'

    def test_func(self):
        return self.request.user.pk == self.get_object().user.pk

    def get_success_url(self):
        return reverse('bike-details', kwargs={'pk': self.object.pk})


class BikeDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Bike
    context_object_name = 'bike'
    success_url = reverse_lazy('my-bikes')
    template_name = 'bikes/delete-bike.html'

    def test_func(self):
        return self.request.user.pk == self.get_object().user.pk

cycleEventsPlanner/templates/bikes/add-bike.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/add-bike.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <title>Add a Bike</title>
</head>
<body>
    <header>
        {% if request.user.is_authenticated %}
            {% include 'common/header-authorized.html' %}
        {% else %}
            {% include 'common/header-anonymous.html' %}
        {% endif %}
    </header>
    <main>
        <div class="outer-container">
            <div class="form-container">
                <h2>Add your Bike:</h2>
                <form method="post">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit">Add Bike</button>
                </form>
            </div>
        </div>
    </main>
    {% include 'common/footer.html' %}
</body>
</html>

cycleEventsPlanner/templates/bikes/bike-details.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/bike-details.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <title>Bike Details</title>
</head>
<body>
    <header>
        {% if request.user.is_authenticated %}
            {% include 'common/header-authorized.html' %}
        {% else %}
            {% include 'common/header-anonymous.html' %}
        {% endif %}
    </header>
    <main>
        <div class="title-container">
            <p>Bike Details:</p>
        </div>
        <div class="outer-container">
            <div class="bike-container">
                {% if bike.picture %}
                    <div class="bike-image">
                        <img src="{{ bike.picture }}" alt="bike picture">
                    </div>
                {% else %}
                    <div class="bike-image">
                        <img src="{% static 'bike-abstract.jpg' %}" alt="no bike picture">
                    </div>
                {% endif %}
                <div class="bike-text">
                    <p id="bike-brand"><strong>{{ bike.manufacturer }}</strong></p>
                    <p id="bike-model"><strong>{{ bike.model }}</strong></p>
                    <p>Type: {{ bike.get_type_display }}</p>
                    <p>Geometry: {{ bike.get_geometry_display }}</p>
                    {% if bike.is_ebike %}
                        <p style="font-style: italic">This is an E-BIKE</p>
                    {% endif %}
                    {% if bike.year %}
                        <p>Model Year: {{ bike.year }}</p>
                    {% endif %}
                    {% if bike.wheel_size and not bike.is_mullet %}
                        <p>Wheel Size (IN): {{ bike.wheel_size }}</p>
                    {% endif %}
                    {% if bike.is_mullet %}
                        <p style="font-style: italic">This is a Mullet Bike</p>
                    {% endif %}
                    {% if bike.weight %}
                        <p>Weight (KG): {{ bike.weight }}</p>
                    {% endif %}
                    {% if bike.user.pk == request.user.pk %}
                        <div class="button-container">
                            <a class="btn" href="{% url 'edit-bike' bike.pk %}"><p>EDIT</p></a>
                            <a class="btn" href="{% url 'delete-bike' bike.pk %}"><p>DELETE</p></a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </main>
    {% include 'common/footer.html' %}
</body>
</html>

cycleEventsPlanner/templates/bikes/bikes-list.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/bikes-list.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <title>Bikes</title>
</head>
<body>
    <header>
        {% if request.user.is_authenticated %}
            {% include 'common/header-authorized.html' %}
        {% else %}
            {% include 'common/header-anonymous.html' %}
        {% endif %}
    </header>
    <main>
        <div class="title-container">
            <p>All Bikes:</p>
        </div>
        <div class="outer-container">
            {% for bike in bikes %}
                <div class="content-container">
                    <a href="{% url 'bike-details' bike.pk %}">
                        <div class="content-container-inner">
                            {% if bike.picture %}
                                <div class="content-image">
                                    <img src="{{ bike.picture }}" alt="bike picture">
                                </div>
                            {% else %}
                                <div class="content-image">
                                    <img src="{% static 'bike-abstract.jpg' %}" alt="no bike picture">
                                </div>
                            {% endif %}
                            <div class="content-text">
                                <div class="top-content-container">
                                    <p>{{ bike.manufacturer }}</p>
                                </div>
                                <div class="mid-content-container">
                                    <p>{{ bike.model }}</p>
                                </div>
                                <div class="lower-content-container">
                                    {% if bike.user.profile %}
                                        <p id="bike-owner-label">bike owner:</p>
                                        <p id="bike-owner">{{ bike.user.profile }}</p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            {% empty %}
            {% endfor %}
        </div>
    </main>
    {% include 'common/footer.html' %}
</body>
</html>

cycleEventsPlanner/templates/bikes/delete-bike.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/delete-bike.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <title>Delete a Bike</title>
</head>
<body>
    <header>
        {% if request.user.is_authenticated %}
            {% include 'common/header-authorized.html' %}
        {% else %}
            {% include 'common/header-anonymous.html' %}
        {% endif %}
    </header>
    <main>
        <div class="outer-container">
            <div class="form-container">
                <h2>Are you sure you want to delete your bike?</h2>
                {% if bike.year %}
                    <p>{{ bike }} {{ bike.year }}</p>
                {% else %}
                    <p>{{ bike }}</p>
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    <button type="submit">DELETE</button>
                </form>
            </div>
        </div>
    </main>
    {% include 'common/footer.html' %}
</body>
</html>

cycleEventsPlanner/templates/bikes/edit-bike.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/edit-bike.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <title>Edit a Bike</title>
</head>
<body>
    <header>
        {% if request.user.is_authenticated %}
            {% include 'common/header-authorized.html' %}
        {% else %}
            {% include 'common/header-anonymous.html' %}
        {% endif %}
    </header>
    <main>
        <div class="outer-container">
            <div class="form-container">
                <h2>Edit your Bike:</h2>
                <form method="post">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit">Edit Bike</button>
                </form>
            </div>
        </div>
    </main>
    {% include 'common/footer.html' %}
</body>
</html>

cycleEventsPlanner/templates/bikes/my-bikes.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/bikes-list.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <title>Bikes</title>
</head>
<body>
    <header>
        {% if request.user.is_authenticated %}
            {% include 'common/header-authorized.html' %}
        {% else %}
            {% include 'common/header-anonymous.html' %}
        {% endif %}
    </header>
    <main>
        <div class="title-container">
            <p>My Owned Bikes: {{ bikes.count }}</p>
        </div>
        <div class="outer-container">
            {% for bike in bikes %}
                <div class="content-container">
                    <a href="{% url 'bike-details' bike.pk %}">
                        <div class="content-container-inner">
                            {% if bike.picture %}
                                <div class="content-image">
                                    <img src="{{ bike.picture }}" alt="bike picture">
                                </div>
                            {% else %}
                                <div class="content-image">
                                    <img src="{% static 'bike-abstract.jpg' %}" alt="no bike picture">
                                </div>
                            {% endif %}
                            <div class="content-text">
                                <div class="top-content-container">
                                    <p>{{ bike.manufacturer }}</p>
                                </div>
                                <div class="mid-content-container">
                                    <p>{{ bike.model }}</p>
                                </div>
                                <div class="lower-content-container">
                                    {% if bike.user.profile %}
                                        <p id="bike-owner-label">bike owner:</p>
                                        <p id="bike-owner">{{ bike.user.profile }}</p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            {% empty %}
            {% endfor %}
        </div>
    </main>
    {% include 'common/footer.html' %}
</body>
</html>