cycleEventsPlanner/bikes/urls.py
from django.urls import path, include

from bikes.views import BikeAddView, BikeDetailView, BikeUpdateView, BikeDeleteView, BikeListView, MyBikesListView

urlpatterns = [
    path('add/', BikeAddView.as_view(), name='add-bike'),
    path('all/', BikeListView.as_view(), name='all-bikes'),
    path('my-bikes/', MyBikesListView.as_view(), name='my-bikes'),
    path('<int:pk>/', include([
        path('', BikeDetailView.as_view(), name='bike-details'),
        path('edit/', BikeUpdateView.as_view(), name='edit-bike'),
        path('delete/', BikeDeleteView.as_view(), name='delete-bike'),
    ]))
]

cycleEventsPlanner/cycleEventsPlanner/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('accounts/', include('accounts.urls')),
    path('bikes/', include('bikes.urls')),
    path('events/', include('events.urls')),
    path('routes/', include('routes.urls')),
    path('gallery/', include('gallery.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cycleEventsPlanner/routes/urls.py
from django.urls import path, include

from routes.views import RouteAddView, RouteDetailView, RouteUpdateView, RouteListView, MyRoutesListView

urlpatterns = [
    path('add/', RouteAddView.as_view(), name='add-route'),
    path('all/', RouteListView.as_view(), name='all-routes'),
    path('my-routes/', MyRoutesListView.as_view(), name='my-routes'),
            path('<int:pk>/', include([
            path('', RouteDetailView.as_view(), name='route-details'),
            path('edit/', RouteUpdateView.as_view(), name='edit-route'),
        ]))
]

cycleEventsPlanner/routes/models.py
from django.contrib.auth import get_user_model
from django.db import models

from common.validators import validate_image_size
from routes.choices import RouteDifficultyChoices, RouteTypeChoices

UserModel = get_user_model()

# Create your models here.
class Route(models.Model):
    name = models.CharField(
        max_length=100,
    )

    difficulty = models.CharField(
        max_length=100,
        choices=RouteDifficultyChoices.choices,
        default=RouteDifficultyChoices.BEGINNER
    )

    type = models.CharField(
        max_length=150,
        choices=RouteTypeChoices.choices,
        default=RouteTypeChoices.AM
    )

    description = models.TextField(
        blank=True,
        null=True,
    )

    distance = models.FloatField(
        blank=True,
        null=True,
    )

    start_point = models.CharField(
        max_length=150,
    )

    end_point = models.CharField(
        max_length=150,
    )

    is_circular = models.BooleanField(
        default=False,
    )

    map_image = models.URLField(
        blank=True,
        null=True,
    )

    route_photo = models.ImageField(
        upload_to='upload/',
        validators=[validate_image_size, ],
        blank=True,
        null=True,
    )

    created_at = models.DateField(
        auto_now_add=True,
    )

    created_by = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
        related_name='routes',
    )

    def __str__(self):
        return self.name

cycleEventsPlanner/routes/forms.py
from django import forms

from routes.models import Route


class RouteBaseForm(forms.ModelForm):
    class Meta:
        model = Route
        exclude = ['created_by', 'created_at', ]
        labels = {
            'name': 'Route Name',
            'difficulty': 'Difficulty',
            'type': 'Route Type',
            'description': 'Brief Description',
            'distance': 'Route Distance',
            'start_point': 'Route Start Point',
            'end_point': 'Route End Point',
            'is_circular': 'Is this a circular route?',
            'map_image': 'Link to Map Image',
            'route_photo': 'Upload a Route Photo',
        }

        widgets = {
            'name': forms.TextInput(
                attrs={
                    'placeholder': 'Your route name:'
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'placeholder': 'Some description... (optional):'
                }
            ),
            'distance': forms.NumberInput(
                attrs={
                    'placeholder': 'Route distance (in KM) (optional):'
                }
            ),
            'start_point': forms.TextInput(
                attrs={
                    'placeholder': 'Start point location or GPS coordinates:'
                }
            ),
            'end_point': forms.TextInput(
                attrs={
                    'placeholder': 'End point location or GPS coordinates:'
                }
            ),
            'map_image': forms.TextInput(
                attrs={
                    'placeholder': 'Link to a map image (optional):'
                }
            ),
            'route_photo' : forms.FileInput(),
        }


class RouteCreateForm(RouteBaseForm):
    pass


class RouteEditForm(RouteBaseForm):
    pass


class RouteDeleteForm(RouteBaseForm):
    pass

cycleEventsPlanner/routes/admin.py
from django.contrib import admin

from routes.models import Route


# Register your models here.
@admin.register(Route)
class RouteAdmin(admin.ModelAdmin):

    ordering = ('-created_at', )

cycleEventsPlanner/routes/apps.py
from django.apps import AppConfig


class RoutesConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'routes'

cycleEventsPlanner/routes/choices.py
from django.db import models


class RouteDifficultyChoices(models.TextChoices):
    BEGINNER = 'beginner', 'Beginner (easy level, best for training)'
    INTERMEDIATE = 'intermediate', 'Intermediate (medium level, lots of fun)'
    ADVANCED = 'advanced', 'Advanced (high level, for skilled raiders)'
    HARD = 'hard', 'Hard (expert level, for bike sports enthusiasts)'
    EXTREME = 'extreme', 'Extreme (extremal level, only top thrill seekers go here)'


class RouteTypeChoices(models.TextChoices):
    ROAD = 'road', 'Road trip (best for road and gravel bike owners)'
    URBAN = 'urban', 'Urban exploring (riding across towns and cities)'
    MIXED = 'mixed', 'Mixed type route (both nature and urban locations)'
    CC = 'crosscountry', 'CrossCountry classic (into the wild)'
    CC_COMPETITION = 'competition', 'CrossCountry competition racetrack (best for CC enthusiasts practicing)'
    AM = 'allmountain', 'AllMountain route type (both uphills and downhills - mountains at its best)'
    TRAIL = 'trail', 'Trail (prepared tracks, mostly downhills)'
    ENDURO = 'enduro', 'Enduro (same as trails, but more technical and extreme)'
    FREERIDE =  'free', 'FreeRide (explore the unexplored)'
    DOWNHILL = 'downhill', 'Downhill (classic DH tracks)'

cycleEventsPlanner/routes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView

from routes.forms import RouteCreateForm, RouteEditForm
from routes.models import Route


# Create your views here.
class RouteAddView(LoginRequiredMixin, CreateView):
    model = Route
    form_class = RouteCreateForm
    template_name = 'routes/add-route.html'
    success_url = reverse_lazy('my-routes')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.save()
        return super().form_valid(form)


class RouteListView(LoginRequiredMixin, ListView):
    model = Route
    context_object_name = 'routes'
    template_name = 'routes/routes-list.html'


class MyRoutesListView(LoginRequiredMixin, ListView):
    model = Route
    context_object_name = 'routes'
    template_name = 'routes/my-routes.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(created_by__pk=self.request.user.pk)
        return queryset


class RouteDetailView(LoginRequiredMixin, DetailView):
    model = Route
    context_object_name = 'route'
    template_name = 'routes/route-details.html'


class RouteUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Route
    form_class = RouteEditForm
    context_object_name = 'route'
    template_name = 'routes/edit-route.html'

    def test_func(self):
        return self.request.user.pk == self.get_object().created_by.pk

    def get_success_url(self):
        return reverse('route-details', kwargs={'pk': self.object.pk})

cycleEventsPlanner/templates/routes/add-route.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/add-route.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <title>Add a Route</title>
</head>
<body>
    <header>
        {% if request.user.is_authenticated %}
            {% include 'common/header-authorized.html' %}
        {% else %}
            {% include 'common/header-anonymous.html' %}
        {% endif %}
    </header>
    <main>
        <div class="outer-container">
            <div class="form-container">
                <h2>Add a Route:</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit">Add Route</button>
                </form>
            </div>
        </div>
    </main>
    {% include 'common/footer.html' %}
</body>
</html>

cycleEventsPlanner/templates/routes/edit-route.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/edit-route.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <title>Edit a Route</title>
</head>
<body>
    <header>
        {% if request.user.is_authenticated %}
            {% include 'common/header-authorized.html' %}
        {% else %}
            {% include 'common/header-anonymous.html' %}
        {% endif %}
    </header>
    <main>
        <div class="outer-container">
            <div class="form-container">
                <h2>Edit your Route:</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit">Edit Route</button>
                </form>
            </div>
        </div>
    </main>
    {% include 'common/footer.html' %}
</body>
</html>

cycleEventsPlanner/templates/routes/my-routes.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/routes-list.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <title>Routes</title>
</head>
<body>
    <header>
        {% if request.user.is_authenticated %}
            {% include 'common/header-authorized.html' %}
        {% else %}
            {% include 'common/header-anonymous.html' %}
        {% endif %}
    </header>
    <main>
        <div class="title-container">
            <p>My Created Routes: {{ routes.count }}</p>
        </div>
        <div class="outer-container">
            {% for route in routes %}
                <div class="content-container">
                    <a href="{% url 'route-details' route.pk %}">
                        <div class="content-container-inner">
                            {% if route.route_photo %}
                                <div class="content-image">
                                    <img src="{{ route.route_photo.url }}" alt="route photo">
                                </div>
                            {% else %}
                                <div class="content-image">
                                    <img src="{% static 'abstract-trail.jpg' %}" alt="no route photo">
                                </div>
                            {% endif %}
                            <div class="content-text">
                                <div class="top-content-container">
                                    <p>{{ route.name }}</p>
                                </div>
                                <div class="mid-content-container">
                                    <p>Start Point: {{ route.start_point }}</p>
                                    <p>End Point: {{ route.end_point }}</p>
                                </div>
                                <div class="lower-content-container">
                                    {% if route.distance %}
                                        <p>Distance (KM): {{ route.distance }}</p>
                                    {% endif %}
                                    {% if route.is_circular %}
                                        <p style="font-style: italic">This is a circular route !</p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            {% empty %}
            {% endfor %}
        </div>
    </main>
    {% include 'common/footer.html' %}
</body>
</html>

cycleEventsPlanner/templates/routes/route-details.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/route-details.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <title>Route Details</title>
</head>
<body>
    <header>
        {% if request.user.is_authenticated %}
            {% include 'common/header-authorized.html' %}
        {% else %}
            {% include 'common/header-anonymous.html' %}
        {% endif %}
    </header>
    <main>
        <div class="title-container">
            <p>Route Details:</p>
        </div>
        <div class="outer-container">
            <div class="route-container">
                {% if route.route_photo %}
                    <div class="route-image">
                        <img src="{{ route.route_photo.url }}" alt="route photo">
                    </div>
                {% else %}
                    <div class="route-image">
                        <img src="{% static 'abstract-trail.jpg' %}" alt="no route photo">
                    </div>
                {% endif %}
                <div class="route-text">
                    <p><strong>{{ route.name }}</strong></p>
                    <p>Difficulty: {{ route.get_difficulty_display }}</p>
                    <p>Type: {{ route.get_type_display }}</p>
                    {% if route.description %}
                        <p>Description: {{ route.description }}</p>
                    {% endif %}
                    {% if route.distance %}
                        <p>Distance (KM): {{ route.distance }}</p>
                    {% endif %}
                    <p>Start Point: {{ route.start_point }}</p>
                    <p>End Point: {{ route.end_point }}</p>
                    {% if route.is_circular %}
                        <p style="font-style: italic">This is a circular route !</p>
                    {% endif %}
                    <p>Date Created : <span>{{ route.created_at }}</span></p>
                    {% if route.created_by.profile %}
                        <p>Created by : <span><a href="{% url 'profile-detail' route.created_by.pk %}" id="route-profile-link">{{ route.created_by.profile }}</a></span></p>
                    {% endif %}
                    {% if route.created_by.pk == request.user.pk %}
                        <div class="button-container">
                            <a class="btn" href="{% url 'edit-route' route.pk %}"><p>EDIT</p></a>
                        </div>
                    {% endif %}
                </div>
                {% if route.map_image %}
                    <div class="route-image">
                        <img src="{{ route.map_image }}" alt="map image">
                    </div>
                {% endif %}
            </div>
        </div>
    </main>
    {% include 'common/footer.html' %}
</body>
</html>

cycleEventsPlanner/templates/routes/routes-list.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/routes-list.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <title>Routes</title>
</head>
<body>
    <header>
        {% if request.user.is_authenticated %}
            {% include 'common/header-authorized.html' %}
        {% else %}
            {% include 'common/header-anonymous.html' %}
        {% endif %}
    </header>
    <main>
        <div class="title-container">
            <p>{{ routes.count }} Total Routes:</p>
        </div>
        <div class="outer-container">
            {% for route in routes %}
                <div class="content-container">
                    <a href="{% url 'route-details' route.pk %}">
                        <div class="content-container-inner">
                            {% if route.route_photo %}
                                <div class="content-image">
                                    <img src="{{ route.route_photo.url }}" alt="route photo">
                                </div>
                            {% else %}
                                <div class="content-image">
                                    <img src="{% static 'abstract-trail.jpg' %}" alt="no route photo">
                                </div>
                            {% endif %}
                            <div class="content-text">
                                <div class="top-content-container">
                                    <p>{{ route.name }}</p>
                                </div>
                                <div class="mid-content-container">
                                    <p>Start Point: {{ route.start_point }}</p>
                                    <p>End Point: {{ route.end_point }}</p>
                                </div>
                                <div class="lower-content-container">
                                    {% if route.distance %}
                                        <p>Distance (KM): {{ route.distance }}</p>
                                    {% endif %}
                                    {% if route.is_circular %}
                                        <p style="font-style: italic">This is a circular route !</p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            {% empty %}
            {% endfor %}
        </div>
    </main>
    {% include 'common/footer.html' %}
</body>
</html>